name: stepzen-schema-checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
    - gitworkflow**
jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install @actions/core glob prettier
    - run: node ./.github/scripts/formatting-check.js
  test-beta-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install stepzen@beta
      - run: |
          mkdir testing
          cd testing
          ../node_modules/stepzen/bin/run init --yes
          ../node_modules/stepzen/bin/run import location
          ../node_modules/stepzen/bin/run validate .
