name: stepzen-schema-checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - gitworkflow**
jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install @actions/core glob prettier
      - run: node ./.github/scripts/formatting-check.js
